image: Visual Studio 2019
build_script:
 - choco install opencover -y
 - dotnet restore "RES.Configuration.sln"
 - dotnet build RES.Configuration.sln /nowarn:1125 /verbosity:quiet 
 - C:\Users\AppVeyor\AppData\Local\Apps\OpenCover\OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test \"RES.Configuration.Test\\RES.Configuration.Test.csproj\"" -register:user -output:"coverage.xml"
 - dotnet build RES.Configuration\RES.Configuration.csproj /t:pack /p:IncludeSymbols=true /nowarn:1125 /verbosity:quiet

test_script:
# upload the code coverage to codcov.io
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"
# code cov token not required for public repos     -t %code_cov_token%
artifacts:
 - path: BuiltDLLs\Debug\*.nupkg 
 - path: coverage.xml
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    subject: 'Build {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
